# -*- coding: utf-8 -*-
"""ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLZ90VSuDvnvBEl5IDBPg65Bwy5eV0aI
"""

import pandas as pd
df = pd.read_csv('SpotifyFeatures.csv')
#feature selection
features = ['danceability', 'energy', 'valence', 'tempo',
            'acousticness', 'instrumentalness', 'liveness',
            'loudness', 'speechiness']
X = df[features]
y = df['popularity']
#normalization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
#pca
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
#kmeans
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)
clusters = kmeans.fit_predict(X_scaled)
df['Cluster'] = clusters
#visualize
import matplotlib.pyplot as plt

plt.figure(figsize=(10,6))
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=clusters, cmap='viridis')
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.title('Music Clusters (by Audio Features)')
plt.colorbar()
plt.show()
# Analyze each cluster
print("\nCluster-wise Audio Feature Averages:")
print(df.groupby('Cluster')[features].mean())